# Generated by Django 4.1.2 on 2022-10-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_author_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='author_id',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
